name: Nope
version: 1.0-SNAPSHOT
main: net.williammck.nope.NopePlugin
api-version: '1.20'
depend: [ProtocolLib]
commands:
  nope:
    description: Turn off Enderman drops and noises.
    usage: /nope
  yep:
    description: Turn on Enderman drops and noises.
    usage: /yep
